services:
  nginx:
    image: nginx:stable
    environment:
      - URL_00001=${CLOUDFLARED_URL}
    command: 
      /bin/sh -c "
      envsubst '$$URL_00001' < /config/nginx.conf.template > /etc/nginx/nginx.conf &&
      nginx -g 'daemon off;'
      "
    volumes:
      - ./infra/nginx:/config
    restart: unless-stopped
    depends_on:
      - client
    networks:
      - app

  cloudflared:
    build: ./infra/cloudflared
    image: tanelpauls/distributed_app_cloudflared
    environment:
      - CLOUDFLARE_TUNNEL_ID=${CLOUDFLARE_TUNNEL_ID}
      - CLOUDFLARED_URL=${CLOUDFLARED_URL}
    volumes:
      - ./infra/cloudflared:/infra/cloudflared
    command: -c "
      envsubst < config.yml.template > config.yml &&
      exec cloudflared --config config.yml tunnel run
      "
    depends_on:
      - nginx
    restart: unless-stopped
    networks:
      - app

  client:
    build: ./client/
    image: tanelpauls/distributed_app_client
    depends_on:
      - event-bus
      - moderation
      - posts
      - query
      - auth
    networks:
      - app
    volumes:
    - ./client:/app
    - /app/node_modules
  
  comments:
    build: ./comments/
    image: tanelpauls/distributed_app_comments
    networks:
      - app
  

  event-bus:
    build: ./event-bus/
    image: tanelpauls/distributed_app_event-bus
    networks:
      - app

  moderation:
    build: ./moderation/
    image: tanelpauls/distributed_app_moderation
    networks:
      - app

  posts:
    build: ./posts/
    image: tanelpauls/distributed_app_posts
    networks:
      - app
  
  query:
    build: ./query/
    image: tanelpauls/distributed_app_query
    networks:
      - app

  auth:
    build: ./auth/
    image: tanelpauls/distributed_app_auth
    networks:
      - app

networks:
  app: