apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: tanelpauls/distributed_app_auth
          env:
            - name: POSTS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTS_DB_USER
            - name: POSTS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTS_DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: JWT_SECRET
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: REFRESH_TOKEN_SECRET