apiVersion: apps/v1
kind: Deployment
metadata: 
  name: comments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: tanelpauls/distributed_app_comments
          env:
            - name: POSTS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTS_DB_USER
            - name: POSTS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTS_DB_PASSWORD