CREATE DATABASE Dist_app
  OWNER ${DB_USER_1}
  ENCODING 'UTF8'
  LC_COLLATE 'C'
  LC_CTYPE 'C'
  TEMPLATE template0;

\connect Dist_app
  
CREATE SCHEMA Dist_app AUTHORIZATION ${DB_USER_1};
  
GRANT USAGE ON SCHEMA ${DB_MAIN_SCHEMA} TO ${DB_USER_1};

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA Dist_app
  TO ${DB_USER_1};

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM PUBLIC;